# Generated by Django 6.1.1 on 2026-09-04 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('laundry', 'Laundry'), ('kitchen', 'Kitchen'), ('shopping', 'Shopping'), ('maintenance', 'Maintenance'), ('pets', 'Pets'), ('other', 'Other')], max_length=20)),
                ('effort_score', models.PositiveSmallIntegerField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('recurrence', models.CharField(choices=[('one-time', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('assignment_type', models.CharField(choices=[('fixed', 'Fixed'), ('alternating', 'Alternating'), ('unassigned', 'Unassigned')], max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ChoreOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('chore_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('laundry', 'Laundry'), ('kitchen', 'Kitchen'), ('shopping', 'Shopping'), ('maintenance', 'Maintenance'), ('pets', 'Pets'), ('other', 'Other')], max_length=20)),
                ('effort_score', models.PositiveSmallIntegerField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='chores.choredefinition')),
            ],
            options={
                'ordering': ('due_date', 'id'),
            },
        ),
        migrations.AddField(
            model_name='choredefinition',
            name='fixed_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_chore_definitions', to='chores.householdmember'),
        ),
        migrations.CreateModel(
            name='ChoreCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField()),
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='chores.choreoccurrence')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chore_completions', to='chores.householdmember')),
            ],
        ),
        migrations.CreateModel(
            name='ChoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='chores.choreoccurrence')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chore_assignments', to='chores.householdmember')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('planned_effort_points', models.PositiveIntegerField(default=0)),
                ('actual_effort_points', models.PositiveIntegerField(default=0)),
                ('completed_chore_count', models.PositiveIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_summaries', to='chores.householdmember')),
            ],
            options={
                'ordering': ('-week_start', 'member_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='choreoccurrence',
            constraint=models.UniqueConstraint(fields=('definition', 'due_date'), name='one_occurrence_per_definition_and_due_date'),
        ),
        migrations.AddConstraint(
            model_name='choreoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('effort_score__gte', 1), ('effort_score__lte', 5)), name='chore_occurrence_effort_score_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='choredefinition',
            constraint=models.CheckConstraint(condition=models.Q(('effort_score__gte', 1), ('effort_score__lte', 5)), name='chore_definition_effort_score_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='weeklysummary',
            constraint=models.UniqueConstraint(fields=('week_start', 'member'), name='one_weekly_summary_per_member'),
        ),
    ]
